### ISSUE TITLE
"llcio.c" not working

### ISSUE THREAD

**Issue by hyanggi** [vanrein/hexio#10]
Hi vanrein,

I tried to run "llcio.c" on my system (Ubuntu 19.10) but it would be stuck at "accept". Maybe my system has bugs. Do you know on which system I can successfully run this program?

Thanks!

**Comment by vanrein** [comment]
Hi,

That's not really a very public package to be honest, but of course you're welcome to use it.  There is an include file that you need to install for llcio that is not commonly present.  I often build without llcio, to be honest, as the functionality is rare.  Does that work for you?

Also, you probably should use CMake to build, not plain make, if you were trying that.

Good luck,
 -Rick

香氣 wrote:
> Hi vanrein,
>
> I tried to run "llcio.c" on my system (Ubuntu 19.10) but it would be stuck at "accept". Maybe my system has bugs. Do you know on which system I can successfully run this program?
>
> Thanks!
>

**Comment by hyanggi** [comment]
Hi Rick,

I am able to build this program just by running "gcc llcio.c". But I have problems running it. The server side would get stuck at "accept". (The client would send out 3 frames but the server wouldn't respond.)

I want to run this program because I'm interested in LLC. I think it's like TCP without IP so I want to try it. I wrote my own program but it would get stuck at "accept". I also tried your program and it would also get stuck at "accept". So I guess it's the problem of my system. I already have the header files and I already have the kernel module. I guess there's a bug somewhere on my system. Do you know on which system you ran this program?

Thanks!

**Comment by hyanggi** [comment]
Hi Rick,

I found the problem to be at my network device. I used my Wi-Fi interface to test but I found that it was not echoing back the connection request frames, and this is why the server was not able to "accept". I changed to an Ethernet interface and made sure that it will echo back the frames. Now your program works and it works very well!

Thanks! This is a very good program! I like it very much because it is able to do reliable connected data transfer directly on Ethernet and without TCP/IP. I think it is very interesting.

Thank you!

**Comment by vanrein** [comment]
Ah,

Wonderful!  I didn't really know what to say and deferred it.

> Thanks! This is a very good program! I like it very much because it is able to do reliable connected data transfer directly on Ethernet and without TCP/IP. I think it is very interesting.

Good.  Please keep in mind it is very local and very premature.  I used it to connect to a piece of hardware and have some simple I/O with it, indeed in a TCP-ish style.  I am sometimes surprised that all LAN traffic is taken over with IP traffic with such interesting alternative tools.

Note that IEEE has retracted the LLC standard, I forgot to mention that.

-Rick
